import { chromium } from "playwright";
const b = await chromium.launch();
const c = await b.newContext({ viewport: { width: 390, height: 844 }, locale: "zh-CN" });
const p = await c.newPage();
const bad = [];
p.on("response", (r) => { if (r.status() >= 400) bad.push(`${r.status()} ${r.url()}`); });
p.on("requestfailed", (r) => bad.push(`FAILED ${r.url()} :: ${r.failure()?.errorText}`));
await p.goto("https://jiaodongtang1-byte.github.io/", { waitUntil: "load", timeout: 45000 });
await p.waitForTimeout(4000);
console.log(bad.length ? bad.join("\n") : "无失败请求");
await b.close();
